name: Create Module Files For GitHub Release

env:
  project_url: 'https://github.com/${{github.repository}}' 
  latest_manifest_url: 'https://github.com/${{github.repository}}/releases/latest/download/module.json'
  release_system_url: 'https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Modify System Manifest With Release-Specific Values
        id: sub_manifest_link_version
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'module.json'
        env:
          VERSION: ${{github.event.release.tag_name}}
          URL: ${{ env.project_url }}
          MANIFEST: ${{ env.latest_manifest_url }}
          DOWNLOAD: ${{ env.release_system_url }}

      - name: Install Dependencies
        run: npm ci

      - name: Build JS and Packs
        run: |
          npm run build --if-present
          if [ -f "public/main.mjs" ]; then mv --force public/main.mjs main.mjs; fi

      - name: Create System Archive
        run: |
          zip --recurse-paths ./module.zip module.json README.md LICENSE main.mjs
          
          if [ -d "styles" ]; then zip -r ./module.zip styles/; fi
          if [ -d "templates" ]; then zip -r ./module.zip templates/; fi
          if [ -d "packs" ]; then zip -r ./module.zip packs/; fi

      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./module.zip'
          tag: ${{github.event.release.tag_name}}
          body: ${{github.event.release.body}}